name: OpenShift-Akbank


env:
  
  REGISTRY: quay.io/altugyildirim
  
  REGISTRY_USER: altugyildirim
  REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}

  OPENSHIFT_SERVER: ${{ secrets.OPENSHIFT_SERVER }}
  OPENSHIFT_TOKEN: ${{ secrets.OPENSHIFT_TOKEN }}
  OPENSHIFT_NAMESPACE: default
  APP_NAME: reversewords
  TAG: workshop

on:
  push:
    branches:
    - dev 
    - main

jobs:
  openshift-ci:
    if: github.ref == 'refs/heads/dev' && github.event_name == 'push'
    name: Build
    runs-on: ubuntu-20.04

    steps:
    - uses: actions/checkout@v2

    - name: Determine app name
      if: env.APP_NAME == ''
      run: |
        echo "APP_NAME=$(basename $PWD)" | tee -a $GITHUB_ENV

    - name: Determine tag
      if: env.TAG == ''
      run: |
        echo "TAG=${GITHUB_SHA::7}" | tee -a $GITHUB_ENV


    - name: Build from Dockerfile
      uses: redhat-actions/buildah-build@v1
      with:
        image: ${{ env.APP_NAME }}
        tag: ${{ env.TAG }}
        dockerfiles: |
          ./Dockerfile

    # https://github.com/redhat-actions/push-to-registry#readme
    - name: Push to registry
      id: push-to-registry
      uses: redhat-actions/push-to-registry@v1
      with:
        image: ${{ env.APP_NAME }}
        tag: ${{ env.TAG }}
        registry: ${{ env.REGISTRY }}
        username: ${{ env.REGISTRY_USER }}
        password: ${{ env.REGISTRY_PASSWORD }}


  openshift-cd-stage:
    if: github.ref == 'refs/heads/dev' && github.event_name == 'push'
    name: CD-stage
    runs-on: ubuntu-20.04
    needs: openshift-ci
    steps:
    - uses: actions/checkout@v2
    - name: Log in to OpenShift
      uses: redhat-actions/oc-login@v1
      with:
        openshift_server_url: ${{ env.OPENSHIFT_SERVER }}
        openshift_token: ${{ env.OPENSHIFT_TOKEN }}
        insecure_skip_tls_verify: true
        namespace: ${{ env.OPENSHIFT_NAMESPACE }}
    - name: Helm
      run: |
       helm upgrade -f ./charts/values.yaml reverseword-stage ./charts --set environment=stage --set namespace=reverse-word-stage-altug --set tag=workshop -n helm-charts


  openshift-cd-prod:
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    name: CD-prod
    runs-on: ubuntu-20.04
    # needs: openshift-ci
    steps:
    - uses: actions/checkout@v2
    - name: Log in to OpenShift
      uses: redhat-actions/oc-login@v1
      with:
        openshift_server_url: ${{ env.OPENSHIFT_SERVER }}
        openshift_token: ${{ env.OPENSHIFT_TOKEN }}
        insecure_skip_tls_verify: true
        namespace: ${{ env.OPENSHIFT_NAMESPACE }}
    - name: Helm
      run: |
       helm upgrade -f ./charts/values.yaml reverseword ./charts --set environment=prod --set namespace=reverse-word-prod-altug --set tag=workshop -n helm-charts
